//! Integration tests for the GGUF loader.
//!
//! These tests exercise the pure-CPU path: binary parse, dequant math,
//! key remap. They do NOT require a CUDA device and run on any host.
//!
//! The `load_real_file` / `load_real_file_shapes` tests are `#[ignore]` by
//! default because they require an actual GGUF file on disk and a working
//! CUDA device. Enable with:
//!
//! ```bash
//! GGUF_TEST_FILE=/path/to/some.gguf \
//!     cargo test --release -- --ignored
//! ```
//!
//! Most dequant tests here use **reference-validated** expected values: the
//! byte arrays and the expected f32 outputs were generated by running
//! llama.cpp's canonical `dequantize_row_q{8_0,4_K,5_K,6_K}` kernels (see
//! `tools/gguf_ref/gen_ref.c`). Earlier versions of these tests derived
//! expected values from the same formula the Rust code implements, which
//! made them self-consistency tautologies rather than correctness proofs.
//! The hand-picked block contents exercise the full state space that the
//! previous "one scale nonzero" tests missed:
//!   - Q4_K: all 8 sub-blocks have distinct non-zero scales AND mins,
//!     exercising both the j<4 AND j>=4 branches of `get_scale_min_k4`
//!     and a non-zero dmin.
//!   - Q5_K: one case covers all 4 qh shift positions (u1/u2 <<= 2
//!     progression); a second case uses qh = 0xAA to alternate hit/miss
//!     and thus validates each individual shift step.
//!   - Q6_K: qh = 0xE4 (0b11100100) extracts 0,1,2,3 at shifts 0,2,4,6
//!     respectively, validating all four 2-bit positions of the qh byte.

use inference_flame::gguf::dequant::dequantize_to_f32;
use inference_flame::gguf::reader::GgufQuantType;
use inference_flame::gguf::{default_rename, read_header};

/// Build a tiny synthetic GGUF blob (version 3, 0 tensors, 1 metadata
/// key) and parse it back via the public `parse_header` path.
#[test]
fn header_parse_synthetic() {
    let mut buf: Vec<u8> = Vec::new();
    buf.extend_from_slice(b"GGUF");
    buf.extend_from_slice(&3u32.to_le_bytes()); // version
    buf.extend_from_slice(&0u64.to_le_bytes()); // n_tensors
    buf.extend_from_slice(&1u64.to_le_bytes()); // n_metadata

    let key = b"general.architecture";
    buf.extend_from_slice(&(key.len() as u64).to_le_bytes());
    buf.extend_from_slice(key);
    buf.extend_from_slice(&8u32.to_le_bytes()); // TYPE_STRING
    let val = b"flux";
    buf.extend_from_slice(&(val.len() as u64).to_le_bytes());
    buf.extend_from_slice(val);

    let tmp_dir = std::env::temp_dir();
    let tmp = tmp_dir.join(format!("gguf_test_synth_{}.gguf", std::process::id()));
    std::fs::write(&tmp, &buf).expect("write tmp");
    let header = read_header(&tmp).expect("parse");
    std::fs::remove_file(&tmp).ok();

    assert_eq!(header.version, 3);
    assert_eq!(header.tensors.len(), 0);
    assert_eq!(header.architecture.as_deref(), Some("flux"));
}

// ---------------------------------------------------------------------------
// Reference-validated dequant values.
//
// These arrays are EMITTED BY llama.cpp's C reference kernels (see
// tools/gguf_ref/gen_ref.c). The byte arrays are the exact on-disk block
// layouts; the float arrays are what `dequantize_row_q*` produces for those
// blocks. Our Rust port must match byte-for-byte.
//
// DO NOT hand-edit these constants — regenerate with:
//   (cd tools/gguf_ref && ./gen_ref > ref_values.rs)
// ---------------------------------------------------------------------------

/// Q8_0_BLOCK_BASIC — d=2.0, qs = [-16, -15, ..., 14, 15].
const Q8_0_BLOCK_BASIC: [u8; 34] = [
    0x00, 0x40, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD,
    0xFE, 0xFF, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D,
    0x0E, 0x0F,
];

const Q8_0_REF_BASIC: [f32; 32] = [
    -32.0, -30.0, -28.0, -26.0, -24.0, -22.0, -20.0, -18.0, -16.0, -14.0, -12.0, -10.0, -8.0, -6.0,
    -4.0, -2.0, 0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0, 22.0, 24.0, 26.0, 28.0,
    30.0,
];

/// Q4_K_BLOCK_DISTINCT_SCALES — d=1.0, dmin=0.5.
/// sc = {3, 5, 7, 11, 13, 17, 19, 23}, m = {1, 2, 4, 8, 16, 32, 33, 48}.
/// qs bytes all 0x3B → low nibble = 0xB = 11, high nibble = 0x3 = 3.
/// This exercises: j<4 and j>=4 branches of get_scale_min_k4, distinct
/// non-zero scales AND mins on every sub-block, dmin != 0.
const Q4_K_BLOCK_DISTINCT_SCALES: [u8; 144] = [
    0x00, 0x3C, 0x00, 0x38, 0x03, 0x45, 0x47, 0x4B, 0x41, 0x82, 0x84, 0xC8, 0x0D, 0x01, 0x13, 0x07,
    0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B,
    0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B,
    0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B,
    0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B,
    0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B,
    0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B,
    0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B,
    0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B, 0x3B,
];

/// Expected 256-element output for Q4_K_BLOCK_DISTINCT_SCALES.
/// Values are constant within each 32-element sub-block; the 8 groups are:
///   group 0 (low nibble,  sc[0]=3,  m[0]=1)  → 3*11 - 0.5*1  = 32.5
///   group 1 (high nibble, sc[1]=5,  m[1]=2)  → 5* 3 - 0.5*2  = 14.0
///   group 2 (low nibble,  sc[2]=7,  m[2]=4)  → 7*11 - 0.5*4  = 75.0
///   group 3 (high nibble, sc[3]=11, m[3]=8)  → 11*3 - 0.5*8  = 29.0
///   group 4 (low nibble,  sc[4]=13, m[4]=16) → 13*11- 0.5*16 = 135.0
///   group 5 (high nibble, sc[5]=17, m[5]=32) → 17*3 - 0.5*32 = 35.0
///   group 6 (low nibble,  sc[6]=19, m[6]=33) → 19*11- 0.5*33 = 192.5
///   group 7 (high nibble, sc[7]=23, m[7]=48) → 23*3 - 0.5*48 = 45.0
const Q4_K_REF_DISTINCT_SCALES_GROUPS: [f32; 8] =
    [32.5, 14.0, 75.0, 29.0, 135.0, 35.0, 192.5, 45.0];

/// Q5_K_BLOCK_ALL_HIGH_BITS — d=1.0, dmin=0.0, sc=all 1, m=all 0.
/// qh = all 0xFF (every bit set). qs = all 0x00.
/// Expected: every element = 1 * 1 * (0 + 16) - 0 = 16.0.
/// Covers: u1,u2 masks at every shift position must find a '1' bit → all 16.
const Q5_K_BLOCK_ALL_HIGH_BITS: [u8; 176] = [
    0x00, 0x3C, 0x00, 0x00, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x01, 0x01,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
];

/// Q5_K_BLOCK_ALTERNATING_QH — same as above but qh = all 0xAA (0b10101010).
/// With u1=1 (bit 0) → miss → lo_hb=0; u2=2 (bit 1) → hit → hi_hb=16.
/// Then u1<<=2 → 4 (bit 2) → miss; u2<<=2 → 8 (bit 3) → hit. Etc.
/// Expected pattern over the 8 sub-blocks (32 elems each):
///   sub 0,2,4,6 (lo-nibble half): y = 0
///   sub 1,3,5,7 (hi-nibble half): y = 16
/// This DIRECTLY validates the u1,u2 <<= 2 shift-progression arithmetic.
const Q5_K_BLOCK_ALTERNATING_QH: [u8; 176] = [
    0x00, 0x3C, 0x00, 0x00, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x01, 0x01,
    0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA,
    0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
];

/// Q6_K_BLOCK_FOUR_SHIFTS — d=1.0, scales[0..16]=all 1, ql=all 0,
/// qh = all 0xE4 (0b11100100).
/// Extracting 2 bits at shifts 0/2/4/6 gives 0/1/2/3 respectively.
/// Hence q1 = (0 | 0<<4) - 32 = -32
///       q2 = (0 | 1<<4) - 32 = -16
///       q3 = (0 | 2<<4) - 32 =   0
///       q4 = (0 | 3<<4) - 32 =  16
/// With all scales = 1 and d = 1 the output within each 128-elem half is
/// [-32]*32, [-16]*32, [0]*32, [16]*32; repeated for the second half.
const Q6_K_BLOCK_FOUR_SHIFTS: [u8; 210] = [
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4,
    0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4,
    0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4,
    0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4, 0xE4,
    0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
    0x00, 0x3C,
];

fn put_f16(out: &mut Vec<u8>, v: f32) {
    let bits = half::f16::from_f32(v).to_bits();
    out.extend_from_slice(&bits.to_le_bytes());
}

/// Q8_0: reference-validated. d=2.0, qs = -16..15 → y = 2*qs.
#[test]
fn dequant_q8_0_reference() {
    let out = dequantize_to_f32(GgufQuantType::Q8_0, &Q8_0_BLOCK_BASIC, 32).unwrap();
    assert_eq!(out.len(), 32);
    for (i, (&got, &expected)) in out.iter().zip(Q8_0_REF_BASIC.iter()).enumerate() {
        assert!(
            (got - expected).abs() < 1e-4,
            "i={i} got={got} expected={expected}"
        );
    }
}

/// Q4_K: reference-validated across all 8 sub-blocks with distinct non-zero
/// scales AND mins. Exercises `get_scale_min_k4` for j<4 AND j>=4.
#[test]
fn dequant_q4_k_reference_distinct_scales() {
    let out = dequantize_to_f32(GgufQuantType::Q4_K, &Q4_K_BLOCK_DISTINCT_SCALES, 256).unwrap();
    assert_eq!(out.len(), 256);
    for group in 0..8 {
        let expected = Q4_K_REF_DISTINCT_SCALES_GROUPS[group];
        for l in 0..32 {
            let i = group * 32 + l;
            assert!(
                (out[i] - expected).abs() < 1e-3,
                "group={group} i={i} got={} expected={}",
                out[i],
                expected
            );
        }
    }
}

/// Q5_K: qh = 0xFF → every bit set → every element's high bit contributes
/// 16 → output uniform at 16.0. Covers all 4 (u1, u2) shift pairs.
#[test]
fn dequant_q5_k_reference_all_high_bits() {
    let out = dequantize_to_f32(GgufQuantType::Q5_K, &Q5_K_BLOCK_ALL_HIGH_BITS, 256).unwrap();
    assert_eq!(out.len(), 256);
    for (i, &v) in out.iter().enumerate() {
        assert!((v - 16.0).abs() < 1e-4, "i={i} got={v} expected 16.0");
    }
}

/// Q5_K: qh = 0xAA → alternating bit pattern.
/// This validates the u1,u2 <<= 2 shift progression directly.
/// Lo-nibble sub-blocks (0,2,4,6) get u1 hitting a '0' → y=0.
/// Hi-nibble sub-blocks (1,3,5,7) get u2 hitting a '1' → y=16.
#[test]
fn dequant_q5_k_reference_alternating_qh() {
    let out = dequantize_to_f32(GgufQuantType::Q5_K, &Q5_K_BLOCK_ALTERNATING_QH, 256).unwrap();
    assert_eq!(out.len(), 256);
    for sub in 0..8 {
        let expected = if sub % 2 == 0 { 0.0 } else { 16.0 };
        for l in 0..32 {
            let i = sub * 32 + l;
            assert!(
                (out[i] - expected).abs() < 1e-4,
                "sub={sub} i={i} got={} expected={}",
                out[i],
                expected
            );
        }
    }
}

/// Q6_K: qh byte 0xE4 contains the four 2-bit values {0, 1, 2, 3} at shifts
/// {0, 2, 4, 6}. With ql=0 and scales=1 the four 32-element groups per half
/// must be [-32, -16, 0, 16]. This validates all four 2-bit qh extractions.
#[test]
fn dequant_q6_k_reference_four_shifts() {
    let out = dequantize_to_f32(GgufQuantType::Q6_K, &Q6_K_BLOCK_FOUR_SHIFTS, 256).unwrap();
    assert_eq!(out.len(), 256);

    // First 128-element half: four 32-elem groups at shifts 0,2,4,6.
    let groups = [-32.0f32, -16.0, 0.0, 16.0];
    for (g, &expected) in groups.iter().enumerate() {
        for l in 0..32 {
            let i = g * 32 + l;
            assert!(
                (out[i] - expected).abs() < 1e-4,
                "half 0 g={g} i={i} got={} expected={}",
                out[i],
                expected
            );
        }
    }
    // Second 128-element half: same pattern (scales[8..16] also all 1).
    for (g, &expected) in groups.iter().enumerate() {
        for l in 0..32 {
            let i = 128 + g * 32 + l;
            assert!(
                (out[i] - expected).abs() < 1e-4,
                "half 1 g={g} i={i} got={} expected={}",
                out[i],
                expected
            );
        }
    }
}

/// Trivial F16 and BF16 passthroughs via the dispatcher.
#[test]
fn f16_bf16_passthrough() {
    let mut bytes = Vec::new();
    for v in [0.0f32, 1.0, -1.0, 2.5, -3.75] {
        put_f16(&mut bytes, v);
    }
    let out = dequantize_to_f32(GgufQuantType::F16, &bytes, 5).unwrap();
    for (got, expected) in out.iter().zip([0.0, 1.0, -1.0, 2.5, -3.75].iter()) {
        assert!((got - expected).abs() < 1e-3);
    }

    let mut bytes = Vec::new();
    for v in [0.0f32, 1.0, -1.0, 2.5, -3.75] {
        let bits = half::bf16::from_f32(v).to_bits();
        bytes.extend_from_slice(&bits.to_le_bytes());
    }
    let out = dequantize_to_f32(GgufQuantType::BF16, &bytes, 5).unwrap();
    for (got, expected) in out.iter().zip([0.0, 1.0, -1.0, 2.5, -3.75].iter()) {
        assert!((got - expected).abs() < 1e-2);
    }
}

/// Four remap cases: each of the three prefixes + a no-prefix passthrough.
#[test]
fn default_rename_cases() {
    assert_eq!(
        default_rename("model.diffusion_model.double_blocks.0.img_attn.qkv.weight"),
        "double_blocks.0.img_attn.qkv.weight"
    );
    assert_eq!(
        default_rename("transformer.single_blocks.0.linear1.weight"),
        "single_blocks.0.linear1.weight"
    );
    assert_eq!(
        default_rename("first_stage_model.encoder.down.0.block.0.conv1.weight"),
        "encoder.down.0.block.0.conv1.weight"
    );
    assert_eq!(
        default_rename("time_in.in_layer.weight"),
        "time_in.in_layer.weight"
    );
}

// ---------------------------------------------------------------------------
// Dim-reversal validation (P1-3 in SKEPTIC_GGUF.md).
//
// The reader reverses GGUF dims on parse so that `dims` matches PyTorch's
// `[out, in, ...]` convention. A wrong-order-but-same-product tensor would
// load silently and multiply without error — producing garbage outputs that
// are impossible to diagnose from a stack trace. This is the highest-risk
// silent failure in the loader.
//
// We cover it in two ways:
//   1. A synthetic GGUF built entirely in memory whose ONE F32 tensor has
//      a known non-square 3D shape. We assert the post-parse Rust-side
//      dims are the exact REVERSE of the dims we wrote. No external file,
//      runs on any host (no CUDA).
//   2. An ignored real-file test keyed on GGUF_TEST_FILE /
//      GGUF_TEST_EXPECTED_SHAPES env vars for when a user wants to check
//      a specific checkpoint's shape registry.
// ---------------------------------------------------------------------------

/// Minimal valid GGUF (version 3) with a single F32 tensor of
/// **GGUF-order** shape [3, 5, 7]. In GGUF convention that's
/// "fastest-moving-first"; our reader must expose this as Rust-side
/// dims = [7, 5, 3] (Pytorch-order).
///
/// Total elements: 3 * 5 * 7 = 105.
/// Byte size: 105 * 4 = 420.
#[test]
fn dim_reversal_from_synthetic_gguf() {
    use inference_flame::gguf::reader::{parse_header, GgufQuantType};

    let mut buf: Vec<u8> = Vec::new();
    // Magic + version.
    buf.extend_from_slice(b"GGUF");
    buf.extend_from_slice(&3u32.to_le_bytes());
    // n_tensors = 1, n_metadata = 0.
    buf.extend_from_slice(&1u64.to_le_bytes());
    buf.extend_from_slice(&0u64.to_le_bytes());

    // Tensor info.
    // - name "t" (length 1 + utf8 byte).
    // - n_dims = 3.
    // - dims = [3, 5, 7] (GGUF storage order, fastest-first).
    // - type = 0 (F32).
    // - data_offset_rel = 0.
    let name = b"t";
    buf.extend_from_slice(&(name.len() as u64).to_le_bytes());
    buf.extend_from_slice(name);
    buf.extend_from_slice(&3u32.to_le_bytes()); // n_dims
    buf.extend_from_slice(&3u64.to_le_bytes()); // dim[0]
    buf.extend_from_slice(&5u64.to_le_bytes()); // dim[1]
    buf.extend_from_slice(&7u64.to_le_bytes()); // dim[2]
    buf.extend_from_slice(&0u32.to_le_bytes()); // ggml_type F32
    buf.extend_from_slice(&0u64.to_le_bytes()); // data_offset_rel

    // Pad to alignment 32, then 420 bytes of zeroed payload.
    while buf.len() % 32 != 0 {
        buf.push(0);
    }
    buf.extend_from_slice(&vec![0u8; 420]);

    let header = parse_header(&buf).expect("parse synthetic GGUF");
    assert_eq!(header.tensors.len(), 1);
    let info = &header.tensors[0];
    assert_eq!(info.name, "t");
    assert_eq!(info.quant, GgufQuantType::F32);

    // The core assertion: dims MUST be reversed from the GGUF storage order.
    // GGUF wrote [3, 5, 7], Rust side must see [7, 5, 3].
    assert_eq!(
        info.dims,
        vec![7usize, 5, 3],
        "dims must be reversed from GGUF storage order"
    );
    assert_eq!(info.n_elements(), 3 * 5 * 7);
}

/// Synthetic GGUF 2D case: GGUF [IN=4, OUT=6] → Rust [OUT=6, IN=4]
/// (this is the linear-weight convention that the rest of flame-core
/// consumes).
#[test]
fn dim_reversal_linear_weight_convention() {
    use inference_flame::gguf::reader::parse_header;

    let mut buf: Vec<u8> = Vec::new();
    buf.extend_from_slice(b"GGUF");
    buf.extend_from_slice(&3u32.to_le_bytes());
    buf.extend_from_slice(&1u64.to_le_bytes()); // n_tensors
    buf.extend_from_slice(&0u64.to_le_bytes()); // n_metadata

    let name = b"linear.weight";
    buf.extend_from_slice(&(name.len() as u64).to_le_bytes());
    buf.extend_from_slice(name);
    buf.extend_from_slice(&2u32.to_le_bytes()); // n_dims
    buf.extend_from_slice(&4u64.to_le_bytes()); // GGUF dim[0] = IN
    buf.extend_from_slice(&6u64.to_le_bytes()); // GGUF dim[1] = OUT
    buf.extend_from_slice(&0u32.to_le_bytes()); // F32
    buf.extend_from_slice(&0u64.to_le_bytes()); // offset rel

    while buf.len() % 32 != 0 {
        buf.push(0);
    }
    buf.extend_from_slice(&vec![0u8; 4 * 6 * 4]); // 24 f32s

    let header = parse_header(&buf).expect("parse");
    let info = &header.tensors[0];
    assert_eq!(
        info.dims,
        vec![6usize, 4],
        "linear weight must be [OUT, IN] after reversal"
    );
}

/// End-to-end load test. Ignored by default — run with
/// `GGUF_TEST_FILE=/path/to/some.gguf cargo test --release -- --ignored`.
/// Requires a working CUDA device.
#[test]
#[ignore]
fn load_real_file() {
    use std::path::Path;
    let path = match std::env::var("GGUF_TEST_FILE") {
        Ok(p) => p,
        Err(_) => {
            eprintln!("GGUF_TEST_FILE not set; skipping load_real_file");
            return;
        }
    };

    let header = read_header(Path::new(&path)).expect("read_header");
    eprintln!(
        "GGUF {} v{} arch={:?} tensors={} alignment={}",
        path,
        header.version,
        header.architecture,
        header.tensors.len(),
        header.alignment
    );
    assert!(!header.tensors.is_empty());

    let device = match flame_core::CudaDevice::new(0) {
        Ok(d) => d,
        Err(e) => {
            eprintln!("no CUDA device available ({e:?}); skipping full load");
            return;
        }
    };

    let tensors = inference_flame::gguf::load_file_gguf(Path::new(&path), device)
        .expect("load_file_gguf");
    assert_eq!(tensors.len(), header.tensors.len());
}

/// Shape verification against a known-good GGUF. Ignored; enable with
/// ```bash
/// GGUF_TEST_FILE=/path/to/some.gguf \
/// GGUF_TEST_EXPECTED_SHAPES="key1:dim1,dim2;key2:dim1,dim2,dim3" \
/// cargo test --release -- --ignored load_real_file_shapes
/// ```
/// This is how the dim-reversal fix (P1-3) gets its real-world check
/// in CI: feed a known checkpoint + the shapes of one or two tensors
/// pulled from the Python `gguf` library / safetensors reference.
#[test]
#[ignore]
fn load_real_file_shapes() {
    use std::path::Path;
    let path = match std::env::var("GGUF_TEST_FILE") {
        Ok(p) => p,
        Err(_) => {
            eprintln!("GGUF_TEST_FILE not set; skipping load_real_file_shapes");
            return;
        }
    };
    let expected_shapes = match std::env::var("GGUF_TEST_EXPECTED_SHAPES") {
        Ok(s) => s,
        Err(_) => {
            eprintln!(
                "GGUF_TEST_EXPECTED_SHAPES not set; skipping (format: \
                 \"key:d1,d2;key2:d1,d2,d3\")"
            );
            return;
        }
    };

    let device = match flame_core::CudaDevice::new(0) {
        Ok(d) => d,
        Err(e) => {
            eprintln!("no CUDA device available ({e:?}); cannot run shape check");
            return;
        }
    };
    let weights = inference_flame::gguf::load_file_gguf(Path::new(&path), device)
        .expect("load_file_gguf");

    for entry in expected_shapes.split(';').filter(|s| !s.is_empty()) {
        let (key, dims_str) = entry
            .split_once(':')
            .unwrap_or_else(|| panic!("bad GGUF_TEST_EXPECTED_SHAPES entry: {entry}"));
        let expected: Vec<usize> = dims_str
            .split(',')
            .map(|s| s.parse().expect("parse dim"))
            .collect();
        let t = weights
            .get(key)
            .unwrap_or_else(|| panic!("key {key} missing from loaded weights"));
        assert_eq!(
            t.shape().dims(),
            expected.as_slice(),
            "shape mismatch for key {key}: got {:?}, expected {:?}",
            t.shape().dims(),
            expected
        );
    }
}
